"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['aliens.py']
DATA_FILES = ['sounds', 'music', 'gfx']
OPTIONS = {'argv_emulation': False, "compressed": True, "optimize": 2, "iconfile": 'gfx/game.icns', 'packages': 'fenix', 'frameworks': ['/usr/local/Cellar/libmikmod/3.2.0/lib/libmikmod.dylib']}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
